name: YouTube Live
on: workflow_dispatch
jobs:
  streaming:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          sudo wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -O /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
      - name: Start Live
        run: |
          yt-dlp -f "best[ext=mp4]" -g "https://www.youtube.com/live/MaQ8_yGHsTk?si=S0rr223JBzGRn81n" | xargs -I {} ffmpeg -re -i {} -c:v libx264 -preset veryfast -b:v 2500k -c:a aac -ar 44100 -f flv "rtmp://a.rtmp.youtube.com/live2/Q12g-s6wc-0y03-0ua5-6e6p"
